import type { AppUser, Book, Order } from "./types";

export const SELLER_ID = "u-seller-approved";
export const PENDING_SELLER_ID = "u-seller-pending";
export const CUSTOMER_ID = "u-customer";
export const ADMIN_ID = "u-admin";

export const initialCategories = [
  "Classic Literature",
  "Academic",
  "Rare & Antique",
  "Fiction",
  "Philosophy",
  "Children's Books",
];

export const initialUsers: AppUser[] = [
  {
    id: CUSTOMER_ID,
    name: "Roaa Alaa",
    email: "roaa@turath.co",
    role: "customer",
    status: "active",
    joined: "2025-11-02",
  },
  {
    id: "u-customer-2",
    name: "Yusuf Karim",
    email: "yusuf@turath.co",
    role: "customer",
    status: "active",
    joined: "2026-01-18",
  },
  {
    id: "u-customer-3",
    name: "Mariam Sobhy",
    email: "mariam@turath.co",
    role: "customer",
    status: "suspended",
    joined: "2026-02-09",
  },
  {
    id: SELLER_ID,
    name: "Dar Al-Warraq",
    email: "warraq@turath.co",
    role: "seller",
    sellerState: "approved",
    status: "active",
    joined: "2025-09-14",
  },
  {
    id: PENDING_SELLER_ID,
    name: "Maktabat Al-Ghusn",
    email: "ghusn@turath.co",
    role: "seller",
    sellerState: "pending",
    status: "active",
    joined: "2026-08-30",
  },
  {
    id: "u-seller-pending-2",
    name: "Sahafat Books",
    email: "sahafat@turath.co",
    role: "seller",
    sellerState: "pending",
    status: "active",
    joined: "2026-09-01",
  },
  {
    id: "u-seller-2",
    name: "Nile Rare Editions",
    email: "nile@turath.co",
    role: "seller",
    sellerState: "approved",
    status: "active",
    joined: "2025-12-21",
  },
  {
    id: ADMIN_ID,
    name: "Turath Steward",
    email: "admin@turath.co",
    role: "admin",
    status: "active",
    joined: "2025-08-01",
  },
];

const spines = ["rust", "navy", "amber", "sage", "crimson"] as const;

export const initialBooks: Book[] = [
  {
    id: "b-1",
    title: "The Prophet",
    titleAr: "النبي",
    author: "Kahlil Gibran",
    price: 180,
    availableQuantity: 4,
    category: "Classic Literature",
    condition: "Like New",
    description:
      "A 1968 reprint of Gibran's meditations on love, work and sorrow. Pages remain supple and the gilt lettering is intact.",
    conditionNotes: "Light shelf wear on the lower spine. No markings inside.",
    sellerId: SELLER_ID,
    spine: "amber",
    images: ["front", "spine", "inner"],
    reviews: [
      {
        id: "r-1",
        author: "Yusuf Karim",
        rating: 5,
        comment: "Arrived wrapped in linen paper. Feels like it was cared for by someone.",
        date: "2026-06-11",
        verified: true,
      },
      {
        id: "r-2",
        author: "Mariam Sobhy",
        rating: 4,
        comment: "Beautiful copy, faint coffee ring on the back cover as described.",
        date: "2026-07-02",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-2",
    title: "Season of Migration to the North",
    titleAr: "موسم الهجرة إلى الشمال",
    author: "Tayeb Salih",
    price: 145,
    availableQuantity: 2,
    category: "Fiction",
    condition: "Good",
    description:
      "Salih's landmark novel of return and rupture, in a well-read paperback edition with a former owner's inscription.",
    conditionNotes: "Inscription on the title page dated 1994. Spine creased.",
    sellerId: SELLER_ID,
    spine: "navy",
    images: ["front", "spine"],
    reviews: [
      {
        id: "r-3",
        author: "Roaa Alaa",
        rating: 5,
        comment: "The inscription made it feel like inheriting a friendship.",
        date: "2026-05-20",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-3",
    title: "Al-Muqaddimah",
    titleAr: "المقدمة",
    author: "Ibn Khaldun",
    price: 620,
    availableQuantity: 1,
    category: "Rare & Antique",
    condition: "Vintage Collector",
    description:
      "Leather-bound Cairo printing with marbled endpapers. A cornerstone of historiography and social thought.",
    conditionNotes: "Hand-tooled leather, slight foxing on early leaves. Binding tight.",
    sellerId: "u-seller-2",
    spine: "crimson",
    images: ["front", "spine", "inner", "detail"],
    reviews: [
      {
        id: "r-4",
        author: "Yusuf Karim",
        rating: 5,
        comment: "Museum-grade. The marbling alone justifies the price.",
        date: "2026-03-14",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-4",
    title: "Organic Chemistry, 7th Edition",
    author: "Paula Bruice",
    price: 260,
    availableQuantity: 9,
    category: "Academic",
    condition: "Acceptable",
    description:
      "Ex-university copy with highlighting across the reaction-mechanism chapters. All plates present.",
    conditionNotes: "Highlighting in chapters 4-11, corner bumps, cover scuffed.",
    sellerId: SELLER_ID,
    spine: "sage",
    images: ["front", "spine"],
    reviews: [],
    flagged: false,
    removed: false,
  },
  {
    id: "b-5",
    title: "Meditations",
    author: "Marcus Aurelius",
    price: 95,
    availableQuantity: 6,
    category: "Philosophy",
    condition: "Good",
    description:
      "Pocket edition of the Stoic notebooks, carried and annotated by a previous reader in pencil.",
    conditionNotes: "Pencil marginalia throughout, erasable. Cover sunned.",
    sellerId: "u-seller-2",
    spine: "rust",
    images: ["front", "spine", "inner"],
    reviews: [
      {
        id: "r-5",
        author: "Mariam Sobhy",
        rating: 4,
        comment: "The previous reader's notes are half the pleasure.",
        date: "2026-04-02",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-6",
    title: "Kalila wa Dimna",
    titleAr: "كليلة ودمنة",
    author: "Ibn al-Muqaffa",
    price: 130,
    availableQuantity: 5,
    category: "Children's Books",
    condition: "Like New",
    description:
      "Illustrated retelling of the animal fables for young readers, with full-colour plates on heavy paper.",
    conditionNotes: "One dog-eared page. Otherwise pristine.",
    sellerId: SELLER_ID,
    spine: "amber",
    images: ["front", "spine"],
    reviews: [
      {
        id: "r-6",
        author: "Roaa Alaa",
        rating: 5,
        comment: "Bought for my niece, ended up rereading it myself.",
        date: "2026-08-12",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-7",
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    price: 165,
    availableQuantity: 3,
    category: "Classic Literature",
    condition: "Good",
    description: "Sun-faded paperback that has travelled through three cities and four readers.",
    conditionNotes: "Faded spine, name crossed out on flyleaf.",
    sellerId: "u-seller-2",
    spine: "sage",
    images: ["front", "spine"],
    reviews: [],
    flagged: false,
    removed: false,
  },
  {
    id: "b-8",
    title: "The Trial",
    author: "Franz Kafka",
    price: 110,
    availableQuantity: 0,
    category: "Fiction",
    condition: "Acceptable",
    description: "Reading copy with a repaired hinge — sturdy enough for one more reader.",
    conditionNotes: "Hinge repaired with archival tape. Text block clean.",
    sellerId: SELLER_ID,
    spine: "navy",
    images: ["front"],
    reviews: [],
    flagged: false,
    removed: false,
  },
  {
    id: "b-9",
    title: "Diwan al-Mutanabbi",
    titleAr: "ديوان المتنبي",
    author: "Al-Mutanabbi",
    price: 340,
    availableQuantity: 2,
    category: "Rare & Antique",
    condition: "Vintage Collector",
    description: "Beirut printing on cream laid paper, gold-stamped boards, ribbon marker intact.",
    conditionNotes: "Gold stamping bright. Minor rubbing at corners.",
    sellerId: "u-seller-2",
    spine: "crimson",
    images: ["front", "spine", "detail"],
    reviews: [
      {
        id: "r-7",
        author: "Yusuf Karim",
        rating: 5,
        comment: "The paper smells like a grandfather's study. Perfect.",
        date: "2026-07-28",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-10",
    title: "Principles of Economics",
    author: "N. Gregory Mankiw",
    price: 210,
    availableQuantity: 7,
    category: "Academic",
    condition: "Good",
    description: "Recent edition released back into circulation by a graduating student.",
    conditionNotes: "Clean text block, small sticker residue on cover.",
    sellerId: SELLER_ID,
    spine: "rust",
    images: ["front", "spine"],
    reviews: [],
    flagged: false,
    removed: false,
  },
  {
    id: "b-11",
    title: "Being and Time",
    author: "Martin Heidegger",
    price: 275,
    availableQuantity: 2,
    category: "Philosophy",
    condition: "Like New",
    description: "Crisp translation with an unopened feel — the previous owner never got past §12.",
    conditionNotes: "Essentially unread. Slight shelf lean.",
    sellerId: "u-seller-2",
    spine: "navy",
    images: ["front", "spine"],
    reviews: [],
    flagged: false,
    removed: false,
  },
  {
    id: "b-12",
    title: "The Little Prince",
    titleAr: "الأمير الصغير",
    author: "Antoine de Saint-Exupéry",
    price: 85,
    availableQuantity: 10,
    category: "Children's Books",
    condition: "Good",
    description: "Bilingual edition with the original watercolours, loved by at least two children.",
    conditionNotes: "Crayon mark on page 31. Binding sound.",
    sellerId: SELLER_ID,
    spine: "sage",
    images: ["front", "spine", "inner"],
    reviews: [
      {
        id: "r-8",
        author: "Mariam Sobhy",
        rating: 4,
        comment: "The crayon mark is now part of the story.",
        date: "2026-06-30",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
];

void spines;

export const initialOrders: Order[] = [
  {
    id: "TRH-1041",
    customerId: CUSTOMER_ID,
    customerName: "Roaa Alaa",
    lines: [
      {
        bookId: "b-1",
        title: "The Prophet",
        author: "Kahlil Gibran",
        price: 180,
        quantity: 1,
        sellerId: SELLER_ID,
      },
    ],
    subtotal: 180,
    shipping: 35,
    tax: 25.2,
    total: 240.2,
    status: "Delivered",
    placedAt: "2026-06-04",
    address: "12 Al-Mu'izz St, Cairo",
  },
  {
    id: "TRH-1058",
    customerId: CUSTOMER_ID,
    customerName: "Roaa Alaa",
    lines: [
      {
        bookId: "b-6",
        title: "Kalila wa Dimna",
        author: "Ibn al-Muqaffa",
        price: 130,
        quantity: 2,
        sellerId: SELLER_ID,
      },
    ],
    subtotal: 260,
    shipping: 35,
    tax: 36.4,
    total: 331.4,
    status: "Shipped",
    placedAt: "2026-08-22",
    address: "12 Al-Mu'izz St, Cairo",
  },
  {
    id: "TRH-1063",
    customerId: "u-customer-2",
    customerName: "Yusuf Karim",
    lines: [
      {
        bookId: "b-9",
        title: "Diwan al-Mutanabbi",
        author: "Al-Mutanabbi",
        price: 340,
        quantity: 1,
        sellerId: "u-seller-2",
      },
      {
        bookId: "b-4",
        title: "Organic Chemistry, 7th Edition",
        author: "Paula Bruice",
        price: 260,
        quantity: 1,
        sellerId: SELLER_ID,
      },
    ],
    subtotal: 600,
    shipping: 35,
    tax: 84,
    total: 719,
    status: "Pending",
    placedAt: "2026-09-08",
    address: "5 Nasr Rd, Alexandria",
  },
  {
    id: "TRH-1066",
    customerId: CUSTOMER_ID,
    customerName: "Roaa Alaa",
    lines: [
      {
        bookId: "b-5",
        title: "Meditations",
        author: "Marcus Aurelius",
        price: 95,
        quantity: 1,
        sellerId: "u-seller-2",
      },
    ],
    subtotal: 95,
    shipping: 35,
    tax: 13.3,
    total: 143.3,
    status: "Pending",
    placedAt: "2026-09-11",
    address: "12 Al-Mu'izz St, Cairo",
  },
];
