import type { AppUser, Book, Order } from "./types";

export const SELLER_ID = "u-seller-approved";
export const PENDING_SELLER_ID = "u-seller-pending";
export const CUSTOMER_ID = "u-customer";
export const ADMIN_ID = "u-admin";

export const initialCategories = [
  "Classic Literature",
  "Academic",
  "Rare & Antique",
  "Fiction",
  "Philosophy",
  "Children's Books",
];

export const initialUsers: AppUser[] = [
  {
    id: CUSTOMER_ID,
    name: "Roaa Alaa",
    email: "roaa@turath.co",
    role: "customer",
    status: "active",
    joined: "2025-11-02",
  },
  {
    id: "u-customer-2",
    name: "Yusuf Karim",
    email: "yusuf@turath.co",
    role: "customer",
    status: "active",
    joined: "2026-01-18",
  },
  {
    id: "u-customer-3",
    name: "Mariam Sobhy",
    email: "mariam@turath.co",
    role: "customer",
    status: "suspended",
    joined: "2026-02-09",
  },
  {
    id: SELLER_ID,
    name: "Dar Al-Warraq",
    email: "warraq@turath.co",
    role: "seller",
    sellerState: "approved",
    status: "active",
    joined: "2025-09-14",
  },
  {
    id: PENDING_SELLER_ID,
    name: "Maktabat Al-Ghusn",
    email: "ghusn@turath.co",
    role: "seller",
    sellerState: "pending",
    status: "active",
    joined: "2026-08-30",
  },
  {
    id: "u-seller-pending-2",
    name: "Sahafat Books",
    email: "sahafat@turath.co",
    role: "seller",
    sellerState: "pending",
    status: "active",
    joined: "2026-09-01",
  },
  {
    id: "u-seller-2",
    name: "Nile Rare Editions",
    email: "nile@turath.co",
    role: "seller",
    sellerState: "approved",
    status: "active",
    joined: "2025-12-21",
  },
  {
    id: ADMIN_ID,
    name: "Turath Steward",
    email: "admin@turath.co",
    role: "admin",
    status: "active",
    joined: "2025-08-01",
  },
  {
    id: "u-admin-com",
    name: "Turath Steward",
    email: "admin@turath.com",
    role: "admin",
    status: "active",
    joined: "2025-08-01",
  },
];

const spines = ["rust", "navy", "amber", "sage", "crimson"] as const;

export const initialBooks: Book[] = [
  {
    id: "b-1",
    title: "The Prophet",
    titleAr: "النبي",
    author: "Kahlil Gibran",
    price: 180,
    availableQuantity: 4,
    category: "Classic Literature",
    condition: "Like New",
    description:
      "A 1968 reprint of Gibran's meditations on love, work and sorrow. Pages remain supple and the gilt lettering is intact.",
    conditionNotes: "Light shelf wear on the lower spine. No markings inside.",
    sellerId: SELLER_ID,
    spine: "amber",
    images: ["front", "spine", "inner"],
    reviews: [
      {
        id: "r-1",
        author: "Yusuf Karim",
        rating: 5,
        comment: "Arrived wrapped in linen paper. Feels like it was cared for by someone.",
        date: "2026-06-11",
        verified: true,
      },
      {
        id: "r-2",
        author: "Mariam Sobhy",
        rating: 4,
        comment: "Beautiful copy, faint coffee ring on the back cover as described.",
        date: "2026-07-02",
        verified: true,
      },
      {
        id: "r-23",
        author: "Farida El-Gendy",
        rating: 5,
        comment: "Gibran's poetic reflections are timeless. Gilt lettering on the spine is stunning.",
        date: "2026-08-14",
        verified: true,
      },
      {
        id: "r-24",
        author: "Ziad Mahmoud",
        rating: 4,
        comment: "Very clean interior with supple, age-toned pages. Excellent condition.",
        date: "2026-09-04",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-2",
    title: "Season of Migration to the North",
    titleAr: "موسم الهجرة إلى الشمال",
    author: "Tayeb Salih",
    price: 145,
    availableQuantity: 2,
    category: "Fiction",
    condition: "Good",
    description:
      "Salih's landmark novel of return and rupture, in a well-read paperback edition with a former owner's inscription.",
    conditionNotes: "Inscription on the title page dated 1994. Spine creased.",
    sellerId: SELLER_ID,
    spine: "navy",
    images: ["front", "spine"],
    reviews: [
      {
        id: "r-3",
        author: "Roaa Alaa",
        rating: 5,
        comment: "The inscription made it feel like inheriting a friendship.",
        date: "2026-05-20",
        verified: true,
      },
      {
        id: "r-25",
        author: "Hana Rostom",
        rating: 5,
        comment: "A masterpiece of Arab literature. Fast delivery and eco-friendly packing.",
        date: "2026-07-18",
        verified: true,
      },
      {
        id: "r-26",
        author: "Dr. Tarek Hegazy",
        rating: 4,
        comment: "Authentic pre-loved paperback with sturdy binding and clear print.",
        date: "2026-08-22",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-3",
    title: "Al-Muqaddimah",
    titleAr: "المقدمة",
    author: "Ibn Khaldun",
    price: 620,
    availableQuantity: 1,
    category: "Rare & Antique",
    condition: "Vintage Collector",
    description:
      "Leather-bound Cairo printing with marbled endpapers. A cornerstone of historiography and social thought.",
    conditionNotes: "Hand-tooled leather, slight foxing on early leaves. Binding tight.",
    sellerId: "u-seller-2",
    spine: "crimson",
    images: ["front", "spine", "inner", "detail"],
    reviews: [
      {
        id: "r-4",
        author: "Yusuf Karim",
        rating: 5,
        comment: "Museum-grade. The marbling alone justifies the price.",
        date: "2026-03-14",
        verified: true,
      },
      {
        id: "r-27",
        author: "Prof. Adel Mansour",
        rating: 5,
        comment: "Hand-tooled leather binding in superb state. A genuine historical gem.",
        date: "2026-06-25",
        verified: true,
      },
      {
        id: "r-28",
        author: "Nour Al-Din",
        rating: 5,
        comment: "Packaging was impenetrable and the book condition exceeded expectations.",
        date: "2026-08-30",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-4",
    title: "Organic Chemistry, 7th Edition",
    author: "Paula Bruice",
    price: 260,
    availableQuantity: 9,
    category: "Academic",
    condition: "Acceptable",
    description:
      "Ex-university copy with highlighting across the reaction-mechanism chapters. All plates present.",
    conditionNotes: "Highlighting in chapters 4-11, corner bumps, cover scuffed.",
    sellerId: SELLER_ID,
    spine: "sage",
    images: ["front", "spine"],
    reviews: [
      {
        id: "r-9",
        author: "Omar Farouk",
        rating: 4,
        comment: "Detailed margin highlights in reaction mechanisms actually helped my study session.",
        date: "2026-08-04",
        verified: true,
      },
      {
        id: "r-10",
        author: "Sarah Nabil",
        rating: 3,
        comment: "Cover shows noticeable shelf wear as described, but all text pages and diagrams are fully intact.",
        date: "2026-07-19",
        verified: true,
      },
      {
        id: "r-29",
        author: "Nada El-Sayed",
        rating: 4,
        comment: "Mechanism flowcharts were very clear. Saved me money on a brand new copy.",
        date: "2026-08-28",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-5",
    title: "Meditations",
    author: "Marcus Aurelius",
    price: 95,
    availableQuantity: 6,
    category: "Philosophy",
    condition: "Good",
    description:
      "Pocket edition of the Stoic notebooks, carried and annotated by a previous reader in pencil.",
    conditionNotes: "Pencil marginalia throughout, erasable. Cover sunned.",
    sellerId: "u-seller-2",
    spine: "rust",
    images: ["front", "spine", "inner"],
    reviews: [
      {
        id: "r-5",
        author: "Mariam Sobhy",
        rating: 4,
        comment: "The previous reader's notes are half the pleasure.",
        date: "2026-04-02",
        verified: true,
      },
      {
        id: "r-11",
        author: "Karim Sami",
        rating: 5,
        comment: "Timeless stoic companion. Fits easily in a jacket pocket.",
        date: "2026-08-15",
        verified: true,
      },
      {
        id: "r-12",
        author: "Hoda Mostafa",
        rating: 4,
        comment: "Smooth paper and comfortable font size for evening reading.",
        date: "2026-09-01",
        verified: true,
      },
      {
        id: "r-30",
        author: "Amr Khaled",
        rating: 5,
        comment: "Essential reading. The pencil notes from the previous reader added so much depth.",
        date: "2026-09-05",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-6",
    title: "Kalila wa Dimna",
    titleAr: "كليلة ودمنة",
    author: "Ibn al-Muqaffa",
    price: 130,
    availableQuantity: 5,
    category: "Children's Books",
    condition: "Like New",
    description:
      "Illustrated retelling of the animal fables for young readers, with full-colour plates on heavy paper.",
    conditionNotes: "One dog-eared page. Otherwise pristine.",
    sellerId: SELLER_ID,
    spine: "amber",
    images: ["front", "spine"],
    reviews: [
      {
        id: "r-6",
        author: "Roaa Alaa",
        rating: 5,
        comment: "Bought for my niece, ended up rereading it myself.",
        date: "2026-08-12",
        verified: true,
      },
      {
        id: "r-13",
        author: "Salma Sherif",
        rating: 5,
        comment: "Vibrant illustrations and clear Arabic typesetting. A family heirloom.",
        date: "2026-09-03",
        verified: true,
      },
      {
        id: "r-31",
        author: "Lina Badr",
        rating: 4,
        comment: "My children loved the animal fables and the illustrations are gorgeous.",
        date: "2026-09-09",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-7",
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    price: 165,
    availableQuantity: 3,
    category: "Classic Literature",
    condition: "Good",
    description: "Sun-faded paperback that has travelled through three cities and four readers.",
    conditionNotes: "Faded spine, name crossed out on flyleaf.",
    sellerId: "u-seller-2",
    spine: "sage",
    images: ["front", "spine"],
    reviews: [
      {
        id: "r-14",
        author: "Youssef Mansour",
        rating: 5,
        comment: "The translation captures Márquez's magical realism effortlessly. Clean binding.",
        date: "2026-07-14",
        verified: true,
      },
      {
        id: "r-15",
        author: "Dina Fouad",
        rating: 4,
        comment: "A book with a soul. Arrived safely in eco-friendly packaging.",
        date: "2026-08-20",
        verified: true,
      },
      {
        id: "r-32",
        author: "Sherif Ezzat",
        rating: 5,
        comment: "A masterpiece. Arrived on time and in great reading condition.",
        date: "2026-09-06",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-8",
    title: "The Trial",
    author: "Franz Kafka",
    price: 110,
    availableQuantity: 0,
    category: "Fiction",
    condition: "Acceptable",
    description: "Reading copy with a repaired hinge — sturdy enough for one more reader.",
    conditionNotes: "Hinge repaired with archival tape. Text block clean.",
    sellerId: SELLER_ID,
    spine: "navy",
    images: ["front"],
    reviews: [
      {
        id: "r-16",
        author: "Dr. Tarek Hegazy",
        rating: 4,
        comment: "Archival tape repair on the hinge is neat and sturdy. Excellent vintage character.",
        date: "2026-06-18",
        verified: true,
      },
      {
        id: "r-33",
        author: "Yusuf Karim",
        rating: 4,
        comment: "Kafka's prose is as haunting as ever. The repaired hinge is completely secure.",
        date: "2026-07-22",
        verified: true,
      },
      {
        id: "r-34",
        author: "Mostafa Radi",
        rating: 4,
        comment: "Great paperback copy, arrived safely and carefully packaged.",
        date: "2026-08-30",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-9",
    title: "Diwan al-Mutanabbi",
    titleAr: "ديوان المتنبي",
    author: "Al-Mutanabbi",
    price: 340,
    availableQuantity: 2,
    category: "Rare & Antique",
    condition: "Vintage Collector",
    description: "Beirut printing on cream laid paper, gold-stamped boards, ribbon marker intact.",
    conditionNotes: "Gold stamping bright. Minor rubbing at corners.",
    sellerId: "u-seller-2",
    spine: "crimson",
    images: ["front", "spine", "detail"],
    reviews: [
      {
        id: "r-7",
        author: "Yusuf Karim",
        rating: 5,
        comment: "The paper smells like a grandfather's study. Perfect.",
        date: "2026-07-28",
        verified: true,
      },
      {
        id: "r-17",
        author: "Roaa Alaa",
        rating: 5,
        comment: "Remarkable poetic edition. The ribbon marker and gold stamping are completely intact.",
        date: "2026-08-10",
        verified: true,
      },
      {
        id: "r-35",
        author: "Mariam Sobhy",
        rating: 5,
        comment: "The classical Arabic commentary in the margins is pure treasure.",
        date: "2026-09-02",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-10",
    title: "Principles of Economics",
    author: "N. Gregory Mankiw",
    price: 210,
    availableQuantity: 7,
    category: "Academic",
    condition: "Good",
    description: "Recent edition released back into circulation by a graduating student.",
    conditionNotes: "Clean text block, small sticker residue on cover.",
    sellerId: SELLER_ID,
    spine: "rust",
    images: ["front", "spine"],
    reviews: [
      {
        id: "r-18",
        author: "Ahmed Reda",
        rating: 4,
        comment: "Crisp graphs and problem sets. Perfect for my macroeconomics coursework.",
        date: "2026-08-25",
        verified: true,
      },
      {
        id: "r-19",
        author: "Nour Al-Din",
        rating: 4,
        comment: "Prompt delivery and exactly matches the syllabus edition.",
        date: "2026-09-02",
        verified: true,
      },
      {
        id: "r-36",
        author: "Hany Mansour",
        rating: 4,
        comment: "Standard university textbook in solid condition at a fraction of the original price.",
        date: "2026-09-10",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-11",
    title: "Being and Time",
    author: "Martin Heidegger",
    price: 275,
    availableQuantity: 2,
    category: "Philosophy",
    condition: "Like New",
    description: "Crisp translation with an unopened feel — the previous owner never got past §12.",
    conditionNotes: "Essentially unread. Slight shelf lean.",
    sellerId: "u-seller-2",
    spine: "navy",
    images: ["front", "spine"],
    reviews: [
      {
        id: "r-20",
        author: "Dr. Tarek Hegazy",
        rating: 5,
        comment: "Immaculate condition, virtually unread with sharp corners and spine.",
        date: "2026-08-29",
        verified: true,
      },
      {
        id: "r-21",
        author: "Omar Adel",
        rating: 4,
        comment: "Excellent translation and great notes on ontology.",
        date: "2026-09-08",
        verified: true,
      },
      {
        id: "r-37",
        author: "Dr. Mona El-Khatib",
        rating: 5,
        comment: "A cornerstone of continental philosophy. Excellent edition and swift shipping.",
        date: "2026-09-12",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
  {
    id: "b-12",
    title: "The Little Prince",
    titleAr: "الأمير الصغير",
    author: "Antoine de Saint-Exupéry",
    price: 85,
    availableQuantity: 10,
    category: "Children's Books",
    condition: "Good",
    description: "Bilingual edition with the original watercolours, loved by at least two children.",
    conditionNotes: "Crayon mark on page 31. Binding sound.",
    sellerId: SELLER_ID,
    spine: "sage",
    images: ["front", "spine", "inner"],
    reviews: [
      {
        id: "r-8",
        author: "Mariam Sobhy",
        rating: 4,
        comment: "The crayon mark is now part of the story.",
        date: "2026-06-30",
        verified: true,
      },
      {
        id: "r-22",
        author: "Layla Hassan",
        rating: 5,
        comment: "Charming bilingual format, lovely for reading before bedtime.",
        date: "2026-08-19",
        verified: true,
      },
      {
        id: "r-38",
        author: "Farah Nabil",
        rating: 5,
        comment: "Delightful bedtime book with original watercolor illustrations.",
        date: "2026-09-01",
        verified: true,
      },
      {
        id: "r-39",
        author: "Roaa Alaa",
        rating: 5,
        comment: "One of my all time favorites. Arrived in beautiful condition.",
        date: "2026-09-07",
        verified: true,
      },
    ],
    flagged: false,
    removed: false,
  },
];

void spines;

export const initialOrders: Order[] = [
  {
    id: "TRH-1041",
    customerId: CUSTOMER_ID,
    customerName: "Roaa Alaa",
    lines: [
      {
        bookId: "b-1",
        title: "The Prophet",
        author: "Kahlil Gibran",
        price: 180,
        quantity: 1,
        sellerId: SELLER_ID,
      },
    ],
    subtotal: 180,
    shipping: 35,
    tax: 25.2,
    total: 240.2,
    status: "Delivered",
    placedAt: "2026-06-04",
    address: "12 Al-Mu'izz St, Cairo",
  },
  {
    id: "TRH-1058",
    customerId: CUSTOMER_ID,
    customerName: "Roaa Alaa",
    lines: [
      {
        bookId: "b-6",
        title: "Kalila wa Dimna",
        author: "Ibn al-Muqaffa",
        price: 130,
        quantity: 2,
        sellerId: SELLER_ID,
      },
    ],
    subtotal: 260,
    shipping: 35,
    tax: 36.4,
    total: 331.4,
    status: "Shipped",
    placedAt: "2026-08-22",
    address: "12 Al-Mu'izz St, Cairo",
  },
  {
    id: "TRH-1063",
    customerId: "u-customer-2",
    customerName: "Yusuf Karim",
    lines: [
      {
        bookId: "b-9",
        title: "Diwan al-Mutanabbi",
        author: "Al-Mutanabbi",
        price: 340,
        quantity: 1,
        sellerId: "u-seller-2",
      },
      {
        bookId: "b-4",
        title: "Organic Chemistry, 7th Edition",
        author: "Paula Bruice",
        price: 260,
        quantity: 1,
        sellerId: SELLER_ID,
      },
    ],
    subtotal: 600,
    shipping: 35,
    tax: 84,
    total: 719,
    status: "Pending",
    placedAt: "2026-09-08",
    address: "5 Nasr Rd, Alexandria",
  },
  {
    id: "TRH-1066",
    customerId: CUSTOMER_ID,
    customerName: "Roaa Alaa",
    lines: [
      {
        bookId: "b-5",
        title: "Meditations",
        author: "Marcus Aurelius",
        price: 95,
        quantity: 1,
        sellerId: "u-seller-2",
      },
    ],
    subtotal: 95,
    shipping: 35,
    tax: 13.3,
    total: 143.3,
    status: "Pending",
    placedAt: "2026-09-11",
    address: "12 Al-Mu'izz St, Cairo",
  },
];
